export const ERROR = {
  USER: {
    NAME_REQUIRED: "Name is required",
    NAME_MIN_LENGTH: "Name must be at least 2 characters long",
    NAME_MAX_LENGTH: "Name cannot exceed 50 characters",
    EMAIL_REQUIRED: "Email is required",
    VALID_EMAIL: "Please provide a valid email address",
    MIN_PASSWORD_LENGTH: "Password must be at least 2 characters long",
    PASSWORD_REQUIRED: "Password is required",
    USER_EXISTS: "User with this email already exists",
    INVALID_CREDENTIALS: "Invalid credentials",
    USER_BLOCKED: "Your account is blocked",
    NOT_FOUND: "User not found",
  },
  TOKEN: {
    ERROR_GENERATING_TOKEN: "An error occurred while generating token",
  },
  BOOK: {
    TITLE_REQUIRED: "Book title is required",
    TITLE_MIN_LENGTH: "Book title must be at least 1 character long",
    TITLE_MAX_LENGTH: "Book title cannot exceed 50 characters",
    AUTHOR_REQUIRED: "Author name is required",
    AUTHOR_MIN_LENGTH: "Author name must be at least 1 character long",
    AUTHOR_MAX_LENGTH: "Author name cannot exceed 50 characters",
    ISBN_REQUIRED: "ISBN is required",
    ISBN_INVALID:
      "Invalid ISBN format. Must be 10-17 digits (with or without hyphens)",
    PUBLISHED_YEAR_REQUIRED: "Published year is required",
    PUBLISHED_YEAR_MIN: "Published year must be greater than or equal to 1000",
    PUBLISHED_YEAR_MAX: "Published year cannot be in the future",
    GENRE_REQUIRED: "Genre is required",
    GENRE_MIN_LENGTH: "Genre must be at least 1 character long",
    GENRE_MAX_LENGTH: "Genre cannot exceed 50 characters",
    TOTAL_COPIES_REQUIRED: "Total copies are required",
    TOTAL_COPIES_MIN: "Total copies must be at least 1",
    AVAILABLE_COPIES_REQUIRED: "Available copies are required",
    AVAILABLE_COPIES_MIN: "Available copies cannot be negative",
    BOOK_EXISTS: "Book with this ISBN already exists",
    NOT_FOUND: "Book Not Found",
    INSUFFICIENT_COPIES: "Insuficient Copies Available.",
  },
  BORROW: {
    USER_ID_REQUIRED: "User ID is required",
    BOOK_ID_REQUIRED: "Book ID is required",
    BORROW_DATE_REQUIRED: "Borrow date is required",
    DUE_DATE_REQUIRED: "Due date is required",
    STATUS_INVALID: "Status must be active, returned, or overdue",
    FINE_MIN: "Fine cannot be negative",
    RETURN_DATE_INVALID: "Return date cannot be before borrow date",
    MAX_BORROW_LIMIT: "Maximum borrow limit reached (5 books)",
    ALREADY_RETURNED: "This Book Already Returned",
    NOT_FOUND: "Borrow Record Found",
    ALREADY_HAVE_OVERDUE_BOOK: " ERROR.BORROW.ALREADY_HAVE_OVERDUE_BOOK",
  },
};
